// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjkuFQkxtn7chozTWemofu9UvPY_LXo4',
    appId: '1:851392610313:web:f33ee630f678d16ce7f8d8',
    messagingSenderId: '851392610313',
    projectId: 'prueba-telconet-d4351',
    authDomain: 'prueba-telconet-d4351.firebaseapp.com',
    databaseURL: 'https://prueba-telconet-d4351-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-telconet-d4351.appspot.com',
    measurementId: 'G-88N0CPJP4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYtRi7S1kqYi5msJQK4ST7jEI9EgkTL8',
    appId: '1:851392610313:android:7f5172bd72f260ffe7f8d8',
    messagingSenderId: '851392610313',
    projectId: 'prueba-telconet-d4351',
    databaseURL: 'https://prueba-telconet-d4351-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-telconet-d4351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKNsYQSTF3tgRsB4HPYFsrH35tKlVp22E',
    appId: '1:851392610313:ios:4d3044aa62bea40ae7f8d8',
    messagingSenderId: '851392610313',
    projectId: 'prueba-telconet-d4351',
    databaseURL: 'https://prueba-telconet-d4351-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-telconet-d4351.appspot.com',
    iosBundleId: 'com.example.pruebaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKNsYQSTF3tgRsB4HPYFsrH35tKlVp22E',
    appId: '1:851392610313:ios:4d3044aa62bea40ae7f8d8',
    messagingSenderId: '851392610313',
    projectId: 'prueba-telconet-d4351',
    databaseURL: 'https://prueba-telconet-d4351-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-telconet-d4351.appspot.com',
    iosBundleId: 'com.example.pruebaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKjkuFQkxtn7chozTWemofu9UvPY_LXo4',
    appId: '1:851392610313:web:c37644db297a2bcae7f8d8',
    messagingSenderId: '851392610313',
    projectId: 'prueba-telconet-d4351',
    authDomain: 'prueba-telconet-d4351.firebaseapp.com',
    databaseURL: 'https://prueba-telconet-d4351-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-telconet-d4351.appspot.com',
    measurementId: 'G-PVFHFQSWZM',
  );
}
